### ISSUE TITLE
All the official distances of galaxies are wrong. Redshift-distance was originally a linear relationship but later on it was contaminated by the SR based formulas that made it into non-linear relationship.

### ISSUE THREAD

**Issue by khuramonline** [a-cosmology-group/acg#71]
All the official distances of galaxies are wrong. Redshift-distance was originally a linear relationship but later on it was contaminated by the SR based formulas that made it into non-linear relationship.

How actually it is implemented is something like... **Limit redshift approaching to infinity, distance approaching to 13.6 billion light years or may be 13.7 billion light years.**

There are learned persons at this forum who might be the authors of online Cosmology Calculators. Anyone can check from any online cosmology calculator that for any insane high value of redshift e.g. 2 million or whatever, the (light travel) distance shall remain 13.6 billion light years or so.

For a simple linear relationship of redshift and distance, the (light travel) distance for a galaxy having redshift 13 corresponds to the distance of 181 billion light years.

Not only redshifts, there is also independent proof that actual distances are at much higher scale than official distances. That proof is Gravitational Lensing.

**Yes, rather than the proof of the existence of "dark matter", Gravitational Lensing is actually a proof that official distances of galaxies are hugely understated.**

I have explained this thing in my second book (2019). Following is link to relevant section of book:

**[Gravitational Lensing Section - Book: "Philosophy Unscrambles Dark Matter" ](https://zenodo.org/record/3817872)**

_Originally posted by @khuramonline in https://github.com/a-cosmology-group/acg/discussions/28#discussioncomment-6258777_

**Comment by marmetl** [comment]
@khuramonline you mistakenly posted this message in `Issues`, which is a section about technical issues with the [ACG repository](https://github.com/a-cosmology-group/acg) and the (webpage](https://a-cosmology-group.github.io/acg/).

Please post this on [Discussions](https://github.com/orgs/a-cosmology-group/discussions).

**Comment by ftessier** [comment]
Note: you can convert Issues to a Discussion, on the right sidebar, second item from the bottom:

![image](https://github.com/a-cosmology-group/acg/assets/1444241/9a34e7b3-263b-4ea7-b347-6438fcb97eb8)

**Comment by khuramonline** [comment]
i just tried to explore some way how one particular comment from one post can be referred in another comment in other post.

**Comment by ftessier** [comment]
Copy link, first item in ellipsis menu:

![image](https://github.com/a-cosmology-group/acg/assets/1444241/273356c2-037a-4996-aa36-d0fbe8d21858)


https://github.com/a-cosmology-group/acg/issues/71#issuecomment-1604473049

**Comment by ftessier** [comment]
To refer to numbered items (issues, pull requests, entire dicussions), you can just type in the number, as in `#54` and github will insert the corresponding link: #54.
