### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by sahil5d** [a-cosmology-group/acg#81]
A few typos on https://a-cosmology-group.github.io/acg/

wording
- Despite of -> Despite

spelling
- newphysics
- cosmologistssuch
- consistentcosmology
- asmany
- tothe

**Comment by marmetl** [comment]
Thanks for spotting that!  Corrected! Next time you can edit the webpage yourself 😮 and get some practice!

The first error was made by the francophone who wrote the text 😊 

It seems the `.html` to `.md` translator might have some problems with <cr><lf> convention differences between Windows and Linux.  Or perhaps the spacebarisbrokenonmykeyboard... These typos might appear on other webpages too.
